version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - /mnt/Docker/compose/backend:/app
      - /app/node_modules
    container_name: goals-backend
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /mnt/Docker/compose/frontend/src:/app/src
    container_name: goals-frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
